version: '3'
services:
  web:
    environment:
      - SECRET_KEY=<your_secret_key>
      - DB_PATH=/data/wireguy.db
    ports:
      - "8000:8000"
    volumes:
      - database:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always

volumes:
  database:

